name: 'Export all variables from other contexts to env variables'
description: 'Utility action that exports all github secrets and vars to environment variables'
author: 'Danilo Körber'
inputs:
  secrets:
    required: true
    description: JSON representation of the secrets, use provided placeholder'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  include:
    required: false
    description: 'Comma-separated list of secrets to export'
  exclude:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  convert:
    required: false
    description: 'Converts secrets name to a specific string format'
  convert_prefix:
    required: false
    description: 'Include prefix (or not) on conversion. True by default'
  override:
    required: false
    description: 'Either to override or not the variable if it already exists'
  value_as_base64:
    required: false
    description: 'Either to convewrt or not the value to base64'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: orange
