name: 'Export all secrets to env variables'
description: 'Utility action that exports all github secrets to environment variables'
author: 'Jose Pereira @oNaiPs'
inputs:
  secrets:
    required: true
    description: JSON representation of the secrets, use provided placeholder'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  include:
    required: false
    description: 'Comma-separated list of secrets to export'
  exclude:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  convert:
    required: false
    description: 'Converts secrets name to a specific string format'
  convert_prefix:
    required: false
    description: 'Include prefix (or not) on conversion. True by default'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: orange
